language: node_js
node_js:
   - "6.9.5"
sudo: false
addons:
  postgresql: "9.4"
services: postgres
before_script:
  - psql -U postgres -f schema/createdb.sql
  - psql -U postgres -d cognicity_grasp -f schema/schema.sql
